# -*- coding: utf-8 -*-
"""
Report Generator workflow (supports multi-turn conversation and visual enhancement)

Features:
- Input: User provides a set of search keywords
- Step 1: Call ResearcherAgent to search top N projects
- Step 2: Iterate through projects, call AnalystAgent for in-depth analysis
- Step 3: Aggregate all analysis results into a Markdown-formatted report
- Step 4 (new): Support user follow-up questions for multi-turn conversation
- Visual enhancement: Generate text progress bars for Star counts

This is a linear workflow demonstrating the basic pattern of multi-Agent collaboration.
"""

import re
from datetime import datetime
from typing import Any, Dict, List, Optional
import time

from src.core.config_manager import ConfigManager
from src.core.guardrails import get_circuit_breaker, filter_sensitive_output
from src.core.logger import get_logger
from src.core.conversation import ConversationManager
from src.agents.analyst_agent import AnalystAgent
from src.agents.researcher_agent import ResearcherAgent

# Import AgentScope tracing
try:
    from agentscope.tracing import trace
except ImportError:
    def trace(name=None):
        def decorator(func):
            return func
        return decorator

logger = get_logger(__name__)


class ReportGenerator:
    """
    Report Generator workflow

    Coordinates ResearcherAgent and AnalystAgent to generate project analysis briefings.

    Attributes:
        researcher: Researcher Agent, responsible for searching projects
        analyst: Analyst Agent, responsible for in-depth project analysis
        config: Configuration manager
        results: Workflow execution results
    """

    # Report template
    REPORT_TEMPLATE = """# GitHub Project Analysis Report

**Generated at**: {timestamp}
**Search Query**: {query}
**Projects Analyzed**: {project_count}

---

## Executive Summary

{executive_summary}

---

## Project Comparison Overview

| Rank | Project | Stars | Language | Maturity | Recommendation |
|------|---------|-------|----------|----------|----------------|
{comparison_table}

---

## Project Details

{project_details}

---

## Overall Assessment

{overall_assessment}

---

*Report automatically generated by GitHub Insight Agent*
"""

    def __init__(
        self,
        config: Optional[ConfigManager] = None,
        researcher: Optional[ResearcherAgent] = None,
        analyst: Optional[AnalystAgent] = None,
        conversation_storage_path: Optional[str] = None,
    ):
        """
        Initialize the report generator

        Args:
            config: Configuration manager
            researcher: Researcher Agent (optional, auto-created if not provided)
            analyst: Analyst Agent (optional, auto-created if not provided)
            conversation_storage_path: Conversation history storage path (optional)
        """
        self.config = config or ConfigManager()
        self.researcher = researcher or ResearcherAgent(config=self.config)
        self.analyst = analyst or AnalystAgent(config=self.config)
        self.results: Dict[str, Any] = {}

        # Conversation manager (supports multi-turn conversation)
        self.conversation = ConversationManager(
            max_turns=5,
            storage_path=conversation_storage_path,
            auto_save=False,
        )

        # Current list of analyzed projects (used for follow-up context)
        self._current_projects: List[Dict[str, Any]] = []

        # Star progress bar reference value (defaults to highest project as 100%)
        self._star_bar_max: int = 0

        logger.info("ReportGenerator initialized (with conversation support)")

    @trace(name="report.execute")
    def execute(
        self,
        query: str,
        num_projects: int = 3,
        sort: str = "stars",
    ) -> str:
        """
        Execute the report generation workflow

        Args:
            query: Search keyword
            num_projects: Number of projects to analyze
            sort: Sort method (stars/forks/updated)

        Returns:
            Report in Markdown format
        """
        # TTI (Time-to-Insight) tracking
        tti_start = time.time()
        step_start = tti_start

        logger.info(f"Starting report generation: '{query}' (num_projects={num_projects})")

        # Start circuit breaker session
        cb = get_circuit_breaker()
        cb.start_session()

        # Clear previous conversation and projects (start a new session)
        self.clear_conversation()

        # Step 1: Search for projects
        logger.info("[Step 1/3] Searching for projects...")
        cb.check()
        search_results = self._search_projects(query, num_projects, sort)
        search_tti = time.time() - step_start
        step_start = time.time()

        if not search_results:
            return self._generate_empty_report(query)

        # Step 2: In-depth analysis of each project
        logger.info("[Step 2/3] Analyzing projects...")
        cb.check()
        analysis_results = self._analyze_projects(search_results)
        analysis_tti = time.time() - step_start
        step_start = time.time()

        # Save current analyzed projects (used for follow-up context)
        self._current_projects = analysis_results

        # Step 3: Generate aggregated report
        logger.info("[Step 3/3] Generating report...")
        cb.check()
        report = self._generate_report(query, search_results, analysis_results)
        report_tti = time.time() - step_start

        # Calculate total TTI
        total_tti = time.time() - tti_start
        logger.info(
            f"TTI metrics: search={search_tti:.1f}s, analysis={analysis_tti:.1f}s, "
            f"report={report_tti:.1f}s, total={total_tti:.1f}s"
        )

        self.results = {
            "query": query,
            "search_results": search_results,
            "analysis_results": analysis_results,
            "report": report,
            "tti": {
                "search": round(search_tti, 2),
                "analysis": round(analysis_tti, 2),
                "report": round(report_tti, 2),
                "total": round(total_tti, 2),
            },
        }

        # Record to conversation history
        self.conversation.add_user_message(f"分析项目：{query}")
        self.conversation.add_assistant_message(
            f"已分析 {len(analysis_results)} 个项目，生成了详细报告。",
            metadata={"type": "report_generated", "project_count": len(analysis_results)},
        )

        logger.info("Report generation completed")
        return report

    def _search_projects(
        self,
        query: str,
        num_projects: int,
        sort: str,
    ) -> List[Dict[str, Any]]:
        """
        Search for projects

        Args:
            query: Search keyword
            num_projects: Number of projects
            sort: Sort method

        Returns:
            List of search results
        """
        try:
            repos = self.researcher.search_and_analyze(
                query=query,
                sort=sort,
                per_page=num_projects,
            )

            # Convert to list of dictionaries
            results = []
            for repo in repos.get("repositories", [])[:num_projects]:
                results.append({
                    "full_name": repo["full_name"],
                    "html_url": repo["html_url"],
                    "stars": repo["stars"],
                    "language": repo["language"],
                    "description": repo["description"],
                    "owner": repo["full_name"].split("/")[0],
                    "repo": repo["full_name"].split("/")[1],
                })

            logger.info(f"Found {len(results)} projects")
            return results

        except Exception as e:
            logger.error(f"Search failed: {e}")
            return []

    def _analyze_projects(
        self,
        projects: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """
        Analyze a list of projects

        Args:
            projects: List of projects

        Returns:
            List of analysis results
        """
        results = []
        for i, project in enumerate(projects, 1):
            logger.info(f"[{i}/{len(projects)}] Analyzing: {project['full_name']}")

            try:
                analysis = self.analyst.analyze_project(
                    owner=project["owner"],
                    repo=project["repo"],
                )
                results.append(analysis)
            except Exception as e:
                logger.error(f"Failed to analyze {project['full_name']}: {e}")
                results.append({
                    "project": project["full_name"],
                    "error": str(e),
                    "analysis": None,
                })

        return results

    @trace(name="report.generate_report")
    def _generate_report(
        self,
        query: str,
        search_results: List[Dict[str, Any]],
        analysis_results: List[Dict[str, Any]],
    ) -> str:
        """
        Generate a report in Markdown format

        Args:
            query: Search keyword
            search_results: Search results
            analysis_results: Analysis results

        Returns:
            Markdown report string
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Generate executive summary
        executive_summary = self._generate_executive_summary(
            search_results, analysis_results
        )

        # Generate project comparison table
        comparison_table = self._generate_comparison_table(analysis_results)

        # Generate project details
        project_details = self._generate_project_details(analysis_results)

        # Generate overall assessment
        overall_assessment = self._generate_overall_assessment(analysis_results)

        # Fill in the template
        report = self.REPORT_TEMPLATE.format(
            timestamp=timestamp,
            query=query,
            project_count=len(search_results),
            executive_summary=executive_summary,
            comparison_table=comparison_table,
            project_details=project_details,
            overall_assessment=overall_assessment,
        )

        return report

    def _generate_executive_summary(
        self,
        search_results: List[Dict[str, Any]],
        analysis_results: List[Dict[str, Any]],
    ) -> str:
        """Generate executive summary"""
        if not analysis_results:
            return "未能获取到有效的分析结果。"

        # Count number of successfully analyzed projects
        successful = sum(
            1 for r in analysis_results if r.get("analysis") and not r.get("error")
        )

        # Calculate total stars
        total_stars = sum(r.get("stars", 0) for r in search_results)
        avg_stars = total_stars // len(search_results) if search_results else 0
        max_stars = max((r.get("stars", 0) for r in search_results), default=0)
        top_project = next(
            (r.get("project", r.get("full_name", ""))
             for r in search_results if r.get("stars") == max_stars),
            ""
        )

        # Extract primary programming languages
        languages = {}
        for r in search_results:
            lang = r.get("language", "Unknown")
            if lang and lang != "Unknown":
                languages[lang] = languages.get(lang, 0) + 1

        # Maturity statistics
        maturity_counts = {}
        for r in analysis_results:
            analysis = r.get("analysis", {})
            if analysis:
                mat = analysis.get("maturity_assessment", "unknown")
                if mat and mat != "unknown":
                    maturity_counts[mat] = maturity_counts.get(mat, 0) + 1

        summary_lines = [
            f"本次搜索共找到 **{len(search_results)}** 个项目，成功深度分析 **{successful}** 个。",
            f"这些项目的总 Star 数超过 **{total_stars:,}** 颗，平均 **{avg_stars:,}** 颗。",
        ]

        if top_project:
            summary_lines.append(f"🏆 最受关注项目：**{top_project}**（⭐ {max_stars:,}）")

        # Language distribution
        if languages:
            lang_str = ", ".join(
                f"{lang} ({count})" for lang, count in sorted(languages.items(), key=lambda x: x[1], reverse=True)
            )
            summary_lines.append(f"主要编程语言：{lang_str}")

        # Maturity overview
        if maturity_counts:
            mat_labels = {
                "mature": "🔵成熟",
                "stable": "🟢稳定",
                "beta": "🟠Beta",
                "early": "🟡早期",
            }
            mat_str = ", ".join(
                f"{mat_labels.get(k, k)} ({v})" for k, v in maturity_counts.items()
            )
            summary_lines.append(f"成熟度分布：{mat_str}")

        summary_lines.extend([
            "",
            "以下是各项目的详细分析：",
        ])

        return "\n".join(summary_lines)

    def _generate_comparison_table(
        self,
        analysis_results: List[Dict[str, Any]],
    ) -> str:
        """Generate project comparison table"""
        maturity_map = {
            "early": "🟡 Early",
            "beta": "🟠 Beta",
            "stable": "🟢 Stable",
            "mature": "🔵 Mature",
        }

        rows = []
        for i, result in enumerate(analysis_results, 1):
            project = result.get("project", "Unknown")
            stars = result.get("stars", 0)
            language = result.get("language", "N/A")
            analysis = result.get("analysis", {})

            maturity = analysis.get("maturity_assessment", "unknown")
            maturity_display = maturity_map.get(maturity, f"? {maturity}")

            rec = analysis.get("recommendation", "")
            if isinstance(rec, str):
                rec_lower = rec.lower()
                if "recommend" in rec_lower:
                    rec_display = "✅ 推荐"
                elif "avoid" in rec_lower:
                    rec_display = "❌ 谨慎"
                else:
                    rec_display = "⚠️ 可考虑"
            else:
                rec_display = "⚠️ 可考虑"

            rows.append(
                f"| {i} | {project} | ⭐ {stars:,} | {language} | {maturity_display} | {rec_display} |"
            )

        return "\n".join(rows)

    def _generate_project_details(
        self,
        analysis_results: List[Dict[str, Any]],
    ) -> str:
        """Generate project details section (with Star progress bar visualization)"""
        details = []

        # Calculate Star progress bar reference value (highest Star count as 100%)
        max_stars = max((r.get("stars", 0) for r in analysis_results), default=1)
        self._star_bar_max = max_stars

        for i, result in enumerate(analysis_results, 1):
            project_name = result.get("project", "Unknown")
            url = result.get("url", "")
            stars = result.get("stars", 0)
            language = result.get("language", "N/A")
            analysis = result.get("analysis", {})

            if result.get("error"):
                details.append(f"### {i}. {project_name}\n⚠️ 分析失败：{result['error']}\n")
                continue

            # Extract analysis results
            core_function = analysis.get("core_function", "Unknown")
            tech_stack = analysis.get("tech_stack", {})
            pain_points = analysis.get("pain_points_solved", [])
            unique_value = analysis.get("unique_value", "")
            recommendation = analysis.get("recommendation", "Unknown")
            competitive = analysis.get("competitive_analysis", "")

            # Build tech stack text
            frameworks = tech_stack.get("frameworks", [])
            dependencies = tech_stack.get("key_dependencies", [])
            lang = tech_stack.get("language", "N/A")

            # Generate Star progress bar
            star_bar = self._generate_star_bar(stars, max_stars)

            # Build project detail
            detail_lines = [
                f"### {i}. [{project_name}]({url})",
                "",
                "| Metric | Value |",
                "|--------|-------|",
                f"| Stars | {star_bar} ⭐ {stars:,} |",
                f"| Language | {language} |",
                "",
                "#### Core Functions",
                core_function,
                "",
                "#### Tech Stack",
                f"- **Language**: {lang}",
            ]

            if frameworks:
                detail_lines.append(f"- **Frameworks**: {', '.join(frameworks)}")
            if dependencies:
                detail_lines.append(f"- **Key Dependencies**: {', '.join(dependencies)}")

            detail_lines.extend([
                "",
                "#### Pain Points Solved",
                self._format_list(pain_points),
            ])

            if unique_value:
                detail_lines.extend([
                    "",
                    "#### Unique Value",
                    unique_value,
                ])

            if competitive:
                detail_lines.extend([
                    "",
                    "#### Competitive Analysis",
                    competitive,
                ])

            detail_lines.extend([
                "",
                "#### Recommendation",
                recommendation,
                "",
                "---",
            ])

            detail = "\n".join(detail_lines)
            details.append(detail)

        return "\n".join(details)

    def _generate_star_bar(self, stars: int, max_stars: int, bar_length: int = 20) -> str:
        """
        Generate a Star text progress bar

        Args:
            stars: Current Star count
            max_stars: Maximum Star count (used as 100% baseline)
            bar_length: Progress bar length

        Returns:
            Progress bar string, e.g.: [██████████----------] 60%
        """
        if max_stars <= 0 or stars <= 0:
            return f"[{'-' * bar_length}] 0%"

        # Calculate percentage
        percentage = min(stars / max_stars, 1.0)
        percentage_display = int(percentage * 100)

        # Calculate filled and empty parts
        filled_length = int(bar_length * percentage)
        empty_length = bar_length - filled_length

        # Generate progress bar
        bar = "█" * filled_length + "-" * empty_length

        return f"[{bar}] {percentage_display}%"

    def _generate_overall_assessment(
        self,
        analysis_results: List[Dict[str, Any]],
    ) -> str:
        """Generate overall assessment section"""
        # Extract all recommendations
        recommendations = []
        for result in analysis_results:
            analysis = result.get("analysis")
            if analysis and isinstance(analysis, dict):
                rec = analysis.get("recommendation", "")
                if rec:
                    recommendations.append(rec)

        # Extract maturity assessments
        maturities = []
        for result in analysis_results:
            analysis = result.get("analysis")
            if analysis and isinstance(analysis, dict):
                mat = analysis.get("maturity_assessment", "")
                if mat:
                    maturities.append(mat)

        assessment_lines = [
            "Based on the above analysis, here is the overall assessment:",
            "",
            "#### Recommendation Statistics",
        ]

        # Count recommendation types
        rec_counts = {"recommend": 0, "consider": 0, "avoid": 0}
        for rec in recommendations:
            rec_lower = rec.lower()
            if "recommend" in rec_lower:
                rec_counts["recommend"] += 1
            elif "avoid" in rec_lower:
                rec_counts["avoid"] += 1
            else:
                rec_counts["consider"] += 1

        assessment_lines.extend([
            f"- 🟢 Recommend: {rec_counts['recommend']}",
            f"- 🟡 Consider: {rec_counts['consider']}",
            f"- 🔴 Avoid: {rec_counts['avoid']}",
        ])

        # Maturity distribution
        if maturities:
            mat_counts = {}
            for mat in maturities:
                mat_lower = mat.lower() if isinstance(mat, str) else str(mat)
                mat_counts[mat_lower] = mat_counts.get(mat_lower, 0) + 1
            mat_display = {
                "mature": "🔵 Mature",
                "stable": "🟢 Stable",
                "beta": "🟠 Beta",
                "early": "🟡 Early",
            }
            assessment_lines.extend([
                "",
                "#### Maturity Distribution",
            ])
            for mat_key, mat_label in mat_display.items():
                count = mat_counts.get(mat_key, 0)
                if count > 0:
                    assessment_lines.append(f"- {mat_label}: {count}")

        # Rank by Stars
        assessment_lines.extend([
            "",
            "#### Overall Ranking",
            "(Based on Star count, maturity, and recommendation)",
            "",
        ])

        for i, result in enumerate(analysis_results, 1):
            project = result.get("project", "Unknown")
            stars = result.get("stars", 0)
            analysis = result.get("analysis", {})
            maturity = analysis.get("maturity_assessment", "unknown")
            rec = analysis.get("recommendation", "")
            rec_label = "✅" if "recommend" in rec.lower() else ("❌" if "avoid" in rec.lower() else "⚠️")
            assessment_lines.append(
                f"{i}. **{project}** - ⭐ {stars:,} | {maturity} | {rec_label}"
            )

        # Tech stack analysis
        languages = {}
        frameworks = {}
        for result in analysis_results:
            analysis = result.get("analysis", {})
            tech = analysis.get("tech_stack", {})
            if tech:
                lang = tech.get("language", "")
                if lang and lang != "N/A":
                    languages[lang] = languages.get(lang, 0) + 1
                for fw in tech.get("frameworks", []):
                    frameworks[fw] = frameworks.get(fw, 0) + 1

        if languages:
            assessment_lines.extend([
                "",
                "#### Technology Ecosystem",
                "",
                "**Programming Language Distribution**:",
            ])
            for lang, count in sorted(languages.items(), key=lambda x: x[1], reverse=True):
                assessment_lines.append(f"- {lang}: {count} projects")

        if frameworks:
            assessment_lines.append("")
            assessment_lines.append("**Common Frameworks**:")
            for fw, count in sorted(frameworks.items(), key=lambda x: x[1], reverse=True)[:5]:
                assessment_lines.append(f"- {fw} ({count})")

        assessment_lines.extend([
            "",
            "#### Overall Suggestions",
            "Based on comprehensive evaluation of project Star count, tech stack maturity, documentation completeness, etc.,",
            "we recommend prioritizing high-Star projects with comprehensive documentation.",
        ])

        return "\n".join(assessment_lines)

    def _generate_empty_report(self, query: str) -> str:
        """Generate an empty report (when search fails)"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        return f"""# GitHub Project Analysis Report

**Generated at**: {timestamp}
**Search Query**: {query}

---

## Executive Summary

No matching projects found. Please try:
1. Changing the search keyword
2. Checking the GitHub Token configuration
3. Confirming network connectivity is normal

---

*Report automatically generated by GitHub Insight Agent*
"""

    @staticmethod
    def _format_list(items: List[str], indent: str = "- ") -> str:
        """Format a list as a string"""
        if not items:
            return "暂无相关信息"
        return "\n".join(f"{indent}{item}" for item in items)

    @trace(name="report.handle_followup")
    def handle_followup(
        self,
        user_query: str,
    ) -> str:
        """
        Handle user follow-up questions (multi-turn conversation support)

        Args:
            user_query: User follow-up question

        Returns:
            Assistant response
        """
        logger.info(f"Handling followup: {user_query}")

        # Record user question
        self.conversation.add_user_message(user_query)

        # Build context
        context = self._build_followup_context()

        # Call LLM to generate response
        response = self._answer_followup(user_query, context)

        # Record assistant answer
        self.conversation.add_assistant_message(response)

        return response

    def _build_followup_context(self) -> str:
        """
        Build follow-up context

        Returns:
            Formatted context string
        """
        context_parts = []

        # Add current analyzed project information
        if self._current_projects:
            context_parts.append("## Currently Analyzed Projects:")
            for proj in self._current_projects:
                context_parts.append(
                    f"- {proj.get('project', 'Unknown')}: "
                    f"{proj.get('analysis', {}).get('core_function', 'N/A')}"
                )

        # Add conversation history (if any)
        conversation_history = self.conversation.get_context_for_prompt()
        if conversation_history:
            context_parts.append("\n## Conversation History:")
            context_parts.append(conversation_history)

        return "\n".join(context_parts)

    def _resolve_repo_query(self, user_query: str) -> Optional[str]:
        """
        Resolve a repo-related followup question to real data.

        Detects queries mentioning a specific repo (owner/repo or project name)
        and fetches actual repo info from GitHub API.

        Args:
            user_query: User followup question

        Returns:
            Formatted repo info string, or None if not a repo query
        """
        # Pattern: owner/repo (may have Chinese chars after)
        owner_repo_match = re.search(
            r"([a-zA-Z0-9_-]+)/([a-zA-Z0-9_.-]+?)(?:[\s(（]|$|的|是|怎么|如何)",
            user_query,
        )
        if owner_repo_match:
            owner, repo = owner_repo_match.group(1), owner_repo_match.group(2)
            try:
                repo_info = self.analyst.github_tool.get_repo_info(owner, repo)
                return (
                    f"## Repository: {repo_info.full_name}\n"
                    f"- Stars: {repo_info.stargazers_count:,}\n"
                    f"- Forks: {repo_info.forks_count:,}\n"
                    f"- Language: {repo_info.language or 'N/A'}\n"
                    f"- Description: {repo_info.description or 'N/A'}\n"
                    f"- URL: {repo_info.html_url}"
                )
            except Exception:
                pass

        # Pattern: project name followed by star/fork/language keywords
        project_keywords = r"(?:star|stars|fork|forks|language|repo|description|issue|issues|commit|commits|pr|pull.?request|release|tag|branch|license|open.?source)"
        name_match = re.search(
            rf"(?:[\s(（]|^)([a-zA-Z][a-zA-Z0-9_.-]{{1,40}})的?[\s(（]?{project_keywords}",
            user_query,
            re.IGNORECASE,
        )
        if name_match:
            project_name = name_match.group(1)
            try:
                repos = self.researcher.github_tool.search_repositories(
                    query=project_name,
                    sort="stars",
                    order="desc",
                    per_page=3,
                )
                if repos:
                    top = repos[0]
                    return (
                        f"## Repository: {top.full_name} (matched from '{project_name}')\n"
                        f"- Stars: {top.stargazers_count:,}\n"
                        f"- Forks: {top.forks_count:,}\n"
                        f"- Language: {top.language or 'N/A'}\n"
                        f"- Description: {top.description or 'N/A'}\n"
                        f"- URL: {top.html_url}"
                    )
            except Exception as e:
                logger.warning(f"Repo search for followup failed: {e}")

        return None

    def _answer_followup(
        self,
        user_query: str,
        context: str,
    ) -> str:
        """
        Call LLM to answer follow-up questions

        Uses intent understanding: if the query requires a GitHub tool call,
        the researcher's LLM intent router handles it. Otherwise, falls back
        to plain LLM chat with context.

        Args:
            user_query: User question
            context: Context information

        Returns:
            Assistant answer
        """
        try:
            # Try intent understanding first
            intent = self.researcher._understand_intent(user_query)
            action = intent["action"]
            params = intent["params"]

            # If it's a tool action, execute it
            result = ""
            if action == "get_repo_info":
                result = self.researcher._execute_get_repo_info(params)
            elif action == "search_repositories":
                result = self.researcher._execute_search(params)
            elif action == "compare_repositories":
                result = self.researcher._execute_compare(
                    params, analyst=self.analyst
                )
            elif action == "analyze_project":
                result = self.researcher._execute_analyze_project(
                    params, analyst=self.analyst
                )
            else:
                result = None  # Signal to fall through to LLM chat

            if result is not None:
                return result
            # For chat action, fall through to LLM with context
        except Exception as e:
            logger.warning(f"Intent routing failed: {e}, falling back to LLM chat")

        # Fall back to LLM chat with context
        try:
            # Try to resolve repo info for the followup question
            repo_data = self._resolve_repo_query(user_query)
            if repo_data:
                context = f"{context}\n\n## 相关仓库数据\n{repo_data}"

            model_wrapper = self.analyst._get_model_wrapper()

            prompt = f"""你是一个专业的 GitHub 项目分析助手。请根据以下上下文回答用户的问题。

{context}

## 用户问题
{user_query}

请给出简洁、专业的回答。如果上下文中没有相关信息，请如实告知。"""

            messages = [
                {"name": "system", "content": "你是一个专业的 GitHub 项目分析助手。", "role": "system"},
                {"name": "user", "content": prompt, "role": "user"},
            ]

            response = model_wrapper(messages=messages)
            content = self.analyst._extract_response_text(response)

            # Filter sensitive data from LLM output
            content = filter_sensitive_output(content)

            logger.info(f"Followup answer generated: {len(content)} chars")

            # Record ReAct thinking process (optional)
            self.conversation.add_assistant_message(
                content,
                metadata={"type": "followup_response"},
            )

            return content

        except Exception as e:
            logger.error(f"Failed to generate followup answer: {e}")
            return f"抱歉，生成回答时出错：{e}"

    def get_conversation_history(self) -> List[Dict[str, Any]]:
        """Get conversation history"""
        return self.conversation.get_full_history()

    def export_conversation(self, output_path: str) -> bool:
        """Export conversation records"""
        return self.conversation.export_markdown(output_path)

    def clear_conversation(self) -> None:
        """Clear conversation history"""
        self.conversation.clear_history()
        self._current_projects.clear()
        logger.info("Conversation cleared")

    def get_results(self) -> Dict[str, Any]:
        """Get workflow execution results"""
        return self.results

    def save_report(self, output_path: str) -> bool:
        """
        Save report to file

        Args:
            output_path: Output file path

        Returns:
            Whether the operation was successful
        """
        if not self.results.get("report"):
            logger.warning("No report to save")
            return False

        try:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(self.results["report"])
            logger.info(f"Report saved to: {output_path}")
            return True
        except Exception as e:
            logger.error(f"Failed to save report: {e}")
            return False
