# -*- coding: utf-8 -*-
"""
Report Generator workflow (supports multi-turn conversation and visual enhancement)

Features:
- Input: User provides a set of search keywords
- Step 1: Call ResearcherAgent to search top N projects
- Step 2: Iterate through projects, call AnalystAgent for in-depth analysis
- Step 3: Aggregate all analysis results into a Markdown-formatted report
- Step 4 (new): Support user follow-up questions for multi-turn conversation
- Visual enhancement: Generate text progress bars for Star counts

This is a linear workflow demonstrating the basic pattern of multi-Agent collaboration.
"""

import re
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from typing import Any, Dict, List, Optional
import time

from src.core.config_manager import ConfigManager
from src.core.contracts import ProjectFact, ProjectAnalysisReport
from src.core.guardrails import get_circuit_breaker, filter_sensitive_output
from src.core.kpi_tracker import KPITracker
from src.core.logger import get_logger
from src.core.conversation import ConversationManager
from src.core.event_bus import (
    EVENT_SEARCH_COMPLETE,
    EVENT_ANALYSIS_START,
    EVENT_ANALYSIS_COMPLETE,
    EVENT_ANALYSIS_BATCH_COMPLETE,
    EVENT_REPORT_COMPLETE,
    get_event_bus,
)
from src.core.feedback import FeedbackCollector, get_feedback_collector
from src.core.feedback_trend import FeedbackTrendAnalyzer
from src.core.llm_cache import get_llm_cache
from src.agents.analyst_agent import AnalystAgent
from src.agents.researcher_agent import ResearcherAgent

# Import AgentScope tracing
try:
    from agentscope.tracing import trace
except ImportError:
    def trace(name=None):
        def decorator(func):
            return func
        return decorator

logger = get_logger(__name__)


class ReportGenerator:
    """
    Report Generator workflow — LLM-driven report orchestrator

    Coordinates ResearcherAgent and AnalystAgent to generate project analysis briefings.

    Attributes:
        researcher: Researcher Agent, responsible for searching projects
        analyst: Analyst Agent, responsible for in-depth project analysis
        config: Configuration manager
        results: Workflow execution results
    """

    @classmethod
    def _build_system_prompt(cls, prompt_key: str = "system_prompt") -> str:
        """Build system prompt from role_kpi.yaml (with fallbacks)."""
        from src.core.prompt_builder import get_system_prompt
        return get_system_prompt("pipeline", prompt_key=prompt_key, use_constraints=False)

    # Report template
    REPORT_TEMPLATE = """# GitHub Project Analysis Report

**Generated at**: {timestamp}
**Search Query**: {query}
**Projects Analyzed**: {project_count}

---

## Executive Summary

{executive_summary}

---

## Project Comparison Overview

| Rank | Project | Stars | Language | Maturity | Recommendation |
|------|---------|-------|----------|----------|----------------|
{comparison_table}

---

## Project Details

{project_details}

---

## Overall Assessment

{overall_assessment}

---

*Report automatically generated by GitHub Insight Agent*
"""

    def __init__(
        self,
        config: Optional[ConfigManager] = None,
        researcher: Optional[ResearcherAgent] = None,
        analyst: Optional[AnalystAgent] = None,
        conversation_storage_path: Optional[str] = None,
    ):
        """
        Initialize the report generator

        Args:
            config: Configuration manager
            researcher: Researcher Agent (optional, auto-created if not provided)
            analyst: Analyst Agent (optional, auto-created if not provided)
            conversation_storage_path: Conversation history storage path (optional)
        """
        self.config = config or ConfigManager()
        self.researcher = researcher or ResearcherAgent(config=self.config)
        self.analyst = analyst or AnalystAgent(config=self.config)
        self.results: Dict[str, Any] = {}
        self.kpi_tracker = KPITracker(self.config)

        # Event bus for pipeline communication (P2-8)
        self.event_bus = get_event_bus()

        # Feedback collector for user feedback loop (P2-9)
        self.feedback_collector: FeedbackCollector = get_feedback_collector()

        # Feedback trend analyzer for north-star metric (P1)
        self.feedback_trend: FeedbackTrendAnalyzer = FeedbackTrendAnalyzer()

        # Conversation manager (supports multi-turn conversation)
        self.conversation = ConversationManager(
            max_turns=5,
            storage_path=conversation_storage_path,
            auto_save=False,
        )

        # Current list of analyzed projects (used for follow-up context)
        self._current_projects: List[Dict[str, Any]] = []

        # Star progress bar reference value (defaults to highest project as 100%)
        self._star_bar_max: int = 0

        logger.info("ReportGenerator initialized (with conversation support)")

    @trace(name="report.execute")
    def execute(
        self,
        query: str,
        num_projects: int = 3,
        sort: str = "stars",
    ) -> str:
        """
        Execute the report generation workflow (Plan-and-Execute + Reflection)

        Flow:
        1. **Plan**: Search projects, determine analysis strategy
        2. **Execute**: Analyze each project with Reflection
        3. **Reflect**: Check report quality, decide if more analysis needed
        4. **Generate**: Output final report

        Args:
            query: Search keyword
            num_projects: Number of projects to analyze
            sort: Sort method (stars/forks/updated)

        Returns:
            Report in Markdown format
        """
        # TTI (Time-to-Insight) tracking
        tti_start = time.time()
        step_start = tti_start

        logger.info(f"Starting report generation: '{query}' (num_projects={num_projects})")

        # Start circuit breaker session
        cb = get_circuit_breaker()
        cb.start_session()

        # Clear previous conversation and projects (start a new session)
        self.clear_conversation()

        # Step 1: Search for projects
        logger.info("[Step 1/4] Searching for projects...")
        cb.check()
        search_results = self._search_projects(query, num_projects, sort)
        self.event_bus.emit(EVENT_SEARCH_COMPLETE, {"query": query, "count": len(search_results)})
        search_tti = time.time() - step_start
        step_start = time.time()

        if not search_results:
            return self._generate_empty_report(query)

        # Plan: Determine analysis strategy based on search results
        plan = self._plan_analysis(query, search_results)
        logger.info(f"[Plan] Strategy: {plan['strategy']} (confidence={plan['confidence']:.0%})")

        # Step 2: In-depth analysis of each project (with Reflection)
        logger.info("[Step 2/4] Analyzing projects...")
        cb.check()
        self.event_bus.emit(EVENT_ANALYSIS_START, {"num_projects": len(search_results)})
        analysis_results = self._analyze_projects(search_results, plan)
        self.event_bus.emit(EVENT_ANALYSIS_BATCH_COMPLETE, {"analyzed": len(analysis_results)})
        analysis_tti = time.time() - step_start
        step_start = time.time()

        # Save current analyzed projects (used for follow-up context)
        self._current_projects = analysis_results

        # Step 3: Reflect on analysis quality
        cb.check()
        reflection = self._reflect_on_analysis(analysis_results, plan)
        if reflection.get("needs_more_analysis"):
            logger.info(f"[Reflection] Needs more analysis: {reflection.get('reason', '')}")
            # Try to analyze additional projects if available
            if len(search_results) > len(analysis_results):
                remaining = search_results[len(analysis_results):]
                logger.info(f"[Reflection] Analyzing {len(remaining)} additional project(s)")
                extra = self._analyze_projects(remaining, plan)
                analysis_results.extend(extra)
                self._current_projects = analysis_results
        reflection_tti = time.time() - step_start
        step_start = time.time()

        # Step 4: Generate aggregated report
        logger.info("[Step 3/4] Generating report...")
        cb.check()
        report = self._generate_report(query, search_results, analysis_results)
        self.event_bus.emit(EVENT_REPORT_COMPLETE, {"report_length": len(report)})
        report_tti = time.time() - step_start

        # Reflect on report quality
        report_reflection = self._reflect_on_report(report, analysis_results)

        # Calculate total TTI
        total_tti = time.time() - tti_start
        logger.info(
            f"TTI metrics: search={search_tti:.1f}s, analysis={analysis_tti:.1f}s, "
            f"reflection={reflection_tti:.1f}s, report={report_tti:.1f}s, "
            f"total={total_tti:.1f}s"
        )

        self.results = {
            "query": query,
            "search_results": search_results,
            "analysis_results": analysis_results,
            "report": report,
            "plan": plan,
            "reflection": reflection,
            "report_reflection": report_reflection,
            "tti": {
                "search": round(search_tti, 2),
                "analysis": round(analysis_tti, 2),
                "reflection": round(reflection_tti, 2),
                "report": round(report_tti, 2),
                "total": round(total_tti, 2),
            },
        }

        # Record to conversation history
        self.conversation.add_user_message(f"分析项目：{query}")
        self.conversation.add_assistant_message(
            f"已分析 {len(analysis_results)} 个项目，生成了详细报告。",
            metadata={"type": "report_generated", "project_count": len(analysis_results)},
        )

        # Track pipeline KPIs
        self.kpi_tracker.track_pipeline_kpis(
            tti_seconds=round(total_tti, 2),
            success=len(analysis_results) > 0,
        )

        logger.info("Report generation completed")
        return report

    def _search_projects(
        self,
        query: str,
        num_projects: int,
        sort: str,
    ) -> List[Dict[str, Any]]:
        """
        Search for projects

        Args:
            query: Search keyword
            num_projects: Number of projects
            sort: Sort method

        Returns:
            List of search results
        """
        try:
            repos = self.researcher.search_and_analyze(
                query=query,
                sort=sort,
                per_page=num_projects,
            )

            # Convert to list of dictionaries with Pydantic validation
            results = []
            for repo in repos.get("repositories", [])[:num_projects]:
                # Map raw API data to ProjectFact contract
                raw = {
                    "owner": repo["full_name"].split("/")[0],
                    "repo": repo["full_name"].split("/")[1],
                    "stars": repo["stars"],
                    "lang": repo.get("language", ""),
                    "readme_snippet": repo.get("readme_snippet"),
                    "trend_score": repo.get("trend_score"),
                    "last_commit_days": repo.get("last_commit_days"),
                    "tags": repo.get("tags", []),
                }
                try:
                    fact = ProjectFact.model_validate(raw)
                except Exception as e:
                    logger.warning(f"ProjectFact validation failed for {raw['owner']}/{raw['repo']}: {e}")
                    fact = None

                result_entry = {
                    "full_name": f"{raw['owner']}/{raw['repo']}",
                    "html_url": repo["html_url"],
                    "stars": raw["stars"],
                    "language": raw["lang"],
                    "description": repo["description"],
                    "owner": raw["owner"],
                    "repo": raw["repo"],
                }
                if fact:
                    # Enrich with validated contract data
                    result_entry["trend_score"] = fact.trend_score
                    result_entry["last_commit_days"] = fact.last_commit_days
                    result_entry["tags"] = fact.tags
                results.append(result_entry)

            logger.info(f"Found {len(results)} projects")
            return results

        except Exception as e:
            logger.error(f"Search failed: {e}")
            return []

    def _analyze_projects(
        self,
        projects: List[Dict[str, Any]],
        plan: Dict[str, Any] = None,
    ) -> List[Dict[str, Any]]:
        """
        Analyze projects concurrently (parallelized with ThreadPoolExecutor)

        Args:
            projects: List of projects
            plan: Analysis strategy from _plan_analysis()

        Returns:
            List of analysis results (in original order)
        """
        strategy = plan.get("strategy", "standard") if plan else "standard"

        def _analyze_single(index: int, project: Dict[str, Any]) -> tuple:
            """Analyze a single project; returns (index, result_or_None)"""
            try:
                analysis = self.analyst.analyze_project(
                    owner=project["owner"],
                    repo=project["repo"],
                )

                # For deep analysis strategy, check if initial analysis is sufficient
                if strategy == "deep" and analysis.get("analysis"):
                    analysis = self._deepen_analysis(project, analysis, plan)

                # Try to validate as ProjectAnalysisReport for structural guarantees
                try:
                    ProjectAnalysisReport.model_validate(
                        analysis,
                        from_attributes=True,
                    )
                    analysis["_validated"] = True
                except Exception:
                    pass

                # Track analyst KPIs
                self.kpi_tracker.track_analyst_kpis(
                    analysis=analysis.get("analysis", {}),
                    report_text=project["full_name"],
                )

                # Emit per-project analysis event (P2-8)
                self.event_bus.emit(EVENT_ANALYSIS_COMPLETE, {
                    "project": project["full_name"],
                    "index": index,
                })

                return (index, analysis)
            except Exception as e:
                logger.error(f"Failed to analyze {project['full_name']}: {e}")
                return (index, {
                    "project": project["full_name"],
                    "error": str(e),
                    "analysis": None,
                })

        results = [None] * len(projects)
        max_workers = min(len(projects), 5)

        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            futures = {
                executor.submit(_analyze_single, i, proj): i
                for i, proj in enumerate(projects)
            }

            for future in as_completed(futures):
                index, result = future.result()
                results[index] = result

        return [r for r in results if r is not None]

    def _plan_analysis(
        self,
        query: str,
        search_results: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Plan analysis strategy using LLM-driven decision (P2-7).

        Falls back to heuristic if LLM call fails.

        Args:
            query: User query
            search_results: Raw search results

        Returns:
            Plan dict with strategy, confidence, and focus areas
        """
        plan = self._llm_decide_strategy(query, search_results)
        if plan is None:
            plan = self._heuristic_plan(search_results)
        return plan

    def _llm_decide_strategy(
        self,
        query: str,
        search_results: List[Dict[str, Any]],
    ) -> Optional[Dict[str, Any]]:
        """Use LLM to decide analysis strategy based on search results (with caching)."""
        # Try cache first
        project_names = [r.get("full_name", "") for r in search_results]
        cached = get_llm_cache().get(query, project_names)
        if cached and cached.get("type") == "strategy":
            logger.info(f"[LLM Cache] strategy hit for query='{query}'")
            plan = cached.get("plan", {})
            plan.setdefault("num_projects", len(search_results))
            return plan

        try:
            model_wrapper = self.analyst._get_model_wrapper()

            results_summary = "\n".join(
                f"- {r.get('full_name', 'unknown')}: "
                f"⭐{r.get('stars', 0)} {r.get('language', 'N/A')}"
                for r in search_results[:10]
            )

            prompt = f"""Given this search query and results, decide the analysis strategy.

Query: {query}

Search Results:
{results_summary}

Decide strategy:
- "quick": low-effort summary (low-quality/low-star results)
- "standard": full analysis (moderate quality)
- "deep": extra scrutiny (high-quality/high-star results)

Also identify focus areas (e.g. "multi-language", "incomplete trend data").

Respond with JSON ONLY:
{{"strategy": "quick|standard|deep", "confidence": 0.XX, "focus_areas": ["..."]}}"""

            messages = [
                {"name": "system", "content": ReportGenerator._build_system_prompt(), "role": "system"},
                {"name": "user", "content": prompt, "role": "user"},
            ]

            response = model_wrapper(messages=messages)
            text = self.analyst._extract_response_text(response)

            # Parse JSON from response
            import json as _json
            text = text.strip()
            # Extract JSON block
            import re as _re
            json_match = _re.search(r"\{.*\}", text, _re.DOTALL)
            if json_match:
                plan = _json.loads(json_match.group())
                plan["confidence"] = max(0.0, min(1.0, plan.get("confidence", 0.5)))
                plan.setdefault("focus_areas", [])
                plan.setdefault("num_projects", len(search_results))
                logger.info(f"[LLM Strategy] {plan['strategy']} (confidence={plan['confidence']:.0%})")

                # Cache the result
                get_llm_cache().put(query, project_names, {
                    "type": "strategy",
                    "plan": plan,
                })

                return plan
        except Exception as e:
            logger.warning(f"LLM strategy decision failed: {e}, falling back to heuristic")
        return None

    def _heuristic_plan(
        self,
        search_results: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """Fallback heuristic strategy decision."""
        plan = {
            "strategy": "standard",
            "confidence": 0.5,
            "focus_areas": [],
            "num_projects": len(search_results),
        }

        avg_stars = sum(r.get("stars", 0) for r in search_results) / len(search_results) if search_results else 0
        has_language = sum(1 for r in search_results if r.get("language") and r["language"] != "Unknown")

        if avg_stars > 5000:
            plan["strategy"] = "deep"
            plan["confidence"] = 0.8
        elif avg_stars > 500:
            plan["strategy"] = "standard"
            plan["confidence"] = 0.6
        else:
            plan["strategy"] = "quick"
            plan["confidence"] = 0.4

        languages = set(r.get("language", "") for r in search_results if r.get("language"))
        if len(languages) > 2:
            plan["focus_areas"].append("multi-language tech stacks")

        has_trend_score = sum(1 for r in search_results if r.get("trend_score") is not None)
        if has_trend_score < len(search_results) * 0.5:
            plan["focus_areas"].append("incomplete trend data")

        plan["confidence"] = min(plan["confidence"], 0.3 + 0.1 * has_language / max(len(search_results), 1))

        return plan

    def _deepen_analysis(
        self,
        project: Dict[str, Any],
        analysis: Dict[str, Any],
        plan: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        For deep strategy: check if initial analysis is sufficient,
        and trigger additional analysis if needed.

        Args:
            project: Project info
            analysis: Initial analysis result
            plan: Analysis plan

        Returns:
            Enhanced analysis dict
        """
        analysis_data = analysis.get("analysis", {})
        if not analysis_data:
            return analysis

        # Check if analysis has enough detail for deep strategy
        pain_points = analysis_data.get("pain_points_solved", [])
        risk_flags = analysis_data.get("risk_flags", [])
        tech_stack = analysis_data.get("tech_stack", {})

        needs_deepening = (
            len(pain_points) < 2 or
            len(risk_flags) < 1 or
            (isinstance(tech_stack, dict) and len(tech_stack.get("frameworks", [])) < 1)
        )

        if needs_deepening:
            logger.info(
                f"[Deepen] Insufficient detail for {project.get('full_name')}, "
                "analysis already complete — will note in report"
            )
            analysis["_deep_analysis"] = {
                "status": "flagged",
                "reason": "Initial analysis lacked depth for deep strategy",
            }
        else:
            analysis["_deep_analysis"] = {
                "status": "sufficient",
            }

        return analysis

    def _reflect_on_analysis(
        self,
        analysis_results: List[Dict[str, Any]],
        plan: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Reflect on overall analysis quality (P2-7: LLM + heuristic hybrid).

        Args:
            analysis_results: List of analysis results
            plan: Analysis plan

        Returns:
            Reflection dict
        """
        successful = sum(
            1 for r in analysis_results
            if r.get("analysis") and not r.get("error")
        )
        total = len(analysis_results)

        reflection = {
            "total": total,
            "successful": successful,
            "success_rate": successful / total if total > 0 else 0,
            "needs_more_analysis": False,
            "reason": "",
        }

        # Try LLM-driven sufficiency check (P2-7)
        llm_decision = self._llm_decide_sufficiency(analysis_results, plan)
        if llm_decision:
            reflection.update(llm_decision)
        else:
            # Fallback to heuristic
            heuristic = self._heuristic_reflection(analysis_results, plan)
            if heuristic["needs_more_analysis"]:
                reflection["needs_more_analysis"] = True
                reflection["reason"] = heuristic["reason"]

        # Check if any analysis lacks reflection metadata
        no_reflection = sum(
            1 for r in analysis_results
            if r.get("analysis") and "_reflection" not in r.get("analysis", {})
        )
        if no_reflection > 0:
            reflection["issues"] = f"{no_reflection} project(s) skipped reflection"

        return reflection

    def _llm_decide_sufficiency(
        self,
        analysis_results: List[Dict[str, Any]],
        plan: Dict[str, Any],
    ) -> Optional[Dict[str, Any]]:
        """Use LLM to decide if analysis results are sufficient (with caching)."""
        # Build cache key from project names in results
        project_names = [r.get("project", r.get("full_name", "")) for r in analysis_results]
        cache_query = f"sufficiency|{plan.get('strategy', 'standard')}"
        cached = get_llm_cache().get(cache_query, project_names)
        if cached and cached.get("type") == "sufficiency":
            logger.info(f"[LLM Cache] sufficiency hit for strategy={plan.get('strategy')}")
            decision = cached.get("decision", {})
            decision.setdefault("decision_method", "llm_cached")
            return decision

        try:
            model_wrapper = self.analyst._get_model_wrapper()

            summary = "\n".join(
                f"- {r.get('project', 'unknown')}: "
                f"{'OK' if r.get('analysis') and not r.get('error') else 'FAILED'}"
                for r in analysis_results
            )

            prompt = f"""Review these analysis results and decide if they are sufficient to generate a report, or if more projects should be analyzed.

Strategy: {plan.get('strategy', 'standard')}
Results:
{summary}

Success rate: {sum(1 for r in analysis_results if r.get('analysis') and not r.get('error'))}/{len(analysis_results)}

Decide:
- "sufficient": proceed to report generation
- "needs_more": analyze more projects first

Respond with JSON ONLY:
{{"decision": "sufficient|needs_more", "reason": "..."}}"""  # noqa: E501

            messages = [
                {"name": "system", "content": ReportGenerator._build_system_prompt(), "role": "system"},
                {"name": "user", "content": prompt, "role": "user"},
            ]

            response = model_wrapper(messages=messages)
            text = self.analyst._extract_response_text(response)

            import json as _json
            import re as _re
            json_match = _re.search(r"\{.*\}", text, _re.DOTALL)
            if json_match:
                decision = _json.loads(json_match.group())
                needs_more = decision.get("decision") == "needs_more"
                result = {
                    "needs_more_analysis": needs_more,
                    "reason": decision.get("reason", ""),
                    "decision_method": "llm",
                }

                # Cache the result
                get_llm_cache().put(cache_query, project_names, {
                    "type": "sufficiency",
                    "decision": result,
                })

                return result
        except Exception as e:
            logger.warning(f"LLM sufficiency check failed: {e}, falling back to heuristic")
        return None

    def _heuristic_reflection(
        self,
        analysis_results: List[Dict[str, Any]],
        plan: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Fallback heuristic sufficiency check."""
        successful = sum(1 for r in analysis_results if r.get("analysis") and not r.get("error"))
        total = len(analysis_results)
        success_rate = successful / total if total > 0 else 0

        if success_rate < 0.5 and total < 5:
            return {
                "needs_more_analysis": True,
                "reason": f"Low success rate ({success_rate:.0%}), need more projects",
            }
        return {"needs_more_analysis": False, "reason": ""}

    def _reflect_on_report(
        self,
        report: str,
        analysis_results: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Reflect on generated report quality.

        Checks:
        - Report has reasonable length
        - All analyzed projects are covered
        - No obvious structural issues

        Args:
            report: Generated report text
            analysis_results: Analysis results used

        Returns:
            Reflection dict
        """
        reflection = {
            "report_length": len(report),
            "projects_covered": len(analysis_results),
            "quality": "good",
        }

        # Check report length
        if len(report) < 500:
            reflection["quality"] = "too_short"
            logger.warning(f"Report is unusually short ({len(report)} chars)")

        # Check for sections that might be empty
        sections = ["Executive Summary", "Project Comparison", "Project Details", "Overall Assessment"]
        missing_sections = [s for s in sections if s not in report]
        if missing_sections:
            reflection["quality"] = "missing_sections"
            reflection["missing_sections"] = missing_sections
            logger.warning(f"Report missing sections: {missing_sections}")

        return reflection

    @trace(name="report.generate_report")
    def _generate_report(
        self,
        query: str,
        search_results: List[Dict[str, Any]],
        analysis_results: List[Dict[str, Any]],
    ) -> str:
        """
        Generate a report in Markdown format

        Args:
            query: Search keyword
            search_results: Search results
            analysis_results: Analysis results

        Returns:
            Markdown report string
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Generate executive summary
        executive_summary = self._generate_executive_summary(
            search_results, analysis_results
        )

        # Generate project comparison table
        comparison_table = self._generate_comparison_table(analysis_results)

        # Generate project details
        project_details = self._generate_project_details(analysis_results)

        # Generate overall assessment
        overall_assessment = self._generate_overall_assessment(analysis_results)

        # Fill in the template
        report = self.REPORT_TEMPLATE.format(
            timestamp=timestamp,
            query=query,
            project_count=len(search_results),
            executive_summary=executive_summary,
            comparison_table=comparison_table,
            project_details=project_details,
            overall_assessment=overall_assessment,
        )

        return report

    def _generate_executive_summary(
        self,
        search_results: List[Dict[str, Any]],
        analysis_results: List[Dict[str, Any]],
    ) -> str:
        """Generate executive summary"""
        if not analysis_results:
            return "未能获取到有效的分析结果。"

        # Count number of successfully analyzed projects
        successful = sum(
            1 for r in analysis_results if r.get("analysis") and not r.get("error")
        )

        # Calculate total stars
        total_stars = sum(r.get("stars", 0) for r in search_results)
        avg_stars = total_stars // len(search_results) if search_results else 0
        max_stars = max((r.get("stars", 0) for r in search_results), default=0)
        top_project = next(
            (r.get("project", r.get("full_name", ""))
             for r in search_results if r.get("stars") == max_stars),
            ""
        )

        # Extract primary programming languages
        languages = {}
        for r in search_results:
            lang = r.get("language", "Unknown")
            if lang and lang != "Unknown":
                languages[lang] = languages.get(lang, 0) + 1

        # Maturity statistics
        maturity_counts = {}
        for r in analysis_results:
            analysis = r.get("analysis", {})
            if analysis:
                mat = analysis.get("maturity_assessment", "unknown")
                if mat and mat != "unknown":
                    maturity_counts[mat] = maturity_counts.get(mat, 0) + 1

        summary_lines = [
            f"本次搜索共找到 **{len(search_results)}** 个项目，成功深度分析 **{successful}** 个。",
            f"这些项目的总 Star 数超过 **{total_stars:,}** 颗，平均 **{avg_stars:,}** 颗。",
        ]

        if top_project:
            summary_lines.append(f"🏆 最受关注项目：**{top_project}**（⭐ {max_stars:,}）")

        # Language distribution
        if languages:
            lang_str = ", ".join(
                f"{lang} ({count})" for lang, count in sorted(languages.items(), key=lambda x: x[1], reverse=True)
            )
            summary_lines.append(f"主要编程语言：{lang_str}")

        # Maturity overview
        if maturity_counts:
            mat_labels = {
                "mature": "🔵成熟",
                "stable": "🟢稳定",
                "beta": "🟠Beta",
                "early": "🟡早期",
            }
            mat_str = ", ".join(
                f"{mat_labels.get(k, k)} ({v})" for k, v in maturity_counts.items()
            )
            summary_lines.append(f"成熟度分布：{mat_str}")

        summary_lines.extend([
            "",
            "以下是各项目的详细分析：",
        ])

        return "\n".join(summary_lines)

    def _generate_comparison_table(
        self,
        analysis_results: List[Dict[str, Any]],
    ) -> str:
        """Generate project comparison table"""
        maturity_map = {
            "early": "🟡 Early",
            "beta": "🟠 Beta",
            "stable": "🟢 Stable",
            "mature": "🔵 Mature",
        }

        rows = []
        for i, result in enumerate(analysis_results, 1):
            project = result.get("project", "Unknown")
            stars = result.get("stars", 0)
            language = result.get("language", "N/A")
            analysis = result.get("analysis", {})

            maturity = analysis.get("maturity_assessment", "unknown")
            maturity_display = maturity_map.get(maturity, f"? {maturity}")

            rec = analysis.get("recommendation", "")
            if isinstance(rec, str):
                rec_lower = rec.lower()
                if "recommend" in rec_lower:
                    rec_display = "✅ 推荐"
                elif "avoid" in rec_lower:
                    rec_display = "❌ 谨慎"
                else:
                    rec_display = "⚠️ 可考虑"
            else:
                rec_display = "⚠️ 可考虑"

            rows.append(
                f"| {i} | {project} | ⭐ {stars:,} | {language} | {maturity_display} | {rec_display} |"
            )

        return "\n".join(rows)

    def _generate_project_details(
        self,
        analysis_results: List[Dict[str, Any]],
    ) -> str:
        """Generate project details section (with Star progress bar visualization)"""
        details = []

        # Calculate Star progress bar reference value (highest Star count as 100%)
        max_stars = max((r.get("stars", 0) for r in analysis_results), default=1)
        self._star_bar_max = max_stars

        for i, result in enumerate(analysis_results, 1):
            project_name = result.get("project", "Unknown")
            url = result.get("url", "")
            stars = result.get("stars", 0)
            language = result.get("language", "N/A")
            analysis = result.get("analysis", {})

            if result.get("error"):
                details.append(f"### {i}. {project_name}\n⚠️ 分析失败：{result['error']}\n")
                continue

            # Extract analysis results
            core_function = analysis.get("core_function", "Unknown")
            tech_stack = analysis.get("tech_stack", {})
            pain_points = analysis.get("pain_points_solved", [])
            unique_value = analysis.get("unique_value", "")
            recommendation = analysis.get("recommendation", "Unknown")
            competitive = analysis.get("competitive_analysis", "")

            # Build tech stack text
            frameworks = tech_stack.get("frameworks", [])
            dependencies = tech_stack.get("key_dependencies", [])
            lang = tech_stack.get("language", "N/A")

            # Generate Star progress bar
            star_bar = self._generate_star_bar(stars, max_stars)

            # Build project detail
            detail_lines = [
                f"### {i}. [{project_name}]({url})",
                "",
                "| Metric | Value |",
                "|--------|-------|",
                f"| Stars | {star_bar} ⭐ {stars:,} |",
                f"| Language | {language} |",
                "",
                "#### Core Functions",
                core_function,
                "",
                "#### Tech Stack",
                f"- **Language**: {lang}",
            ]

            if frameworks:
                detail_lines.append(f"- **Frameworks**: {', '.join(frameworks)}")
            if dependencies:
                detail_lines.append(f"- **Key Dependencies**: {', '.join(dependencies)}")

            detail_lines.extend([
                "",
                "#### Pain Points Solved",
                self._format_list(pain_points),
            ])

            if unique_value:
                detail_lines.extend([
                    "",
                    "#### Unique Value",
                    unique_value,
                ])

            if competitive:
                detail_lines.extend([
                    "",
                    "#### Competitive Analysis",
                    competitive,
                ])

            detail_lines.extend([
                "",
                "#### Recommendation",
                recommendation,
                "",
                "---",
            ])

            detail = "\n".join(detail_lines)
            details.append(detail)

        return "\n".join(details)

    def _generate_star_bar(self, stars: int, max_stars: int, bar_length: int = 20) -> str:
        """
        Generate a Star text progress bar

        Args:
            stars: Current Star count
            max_stars: Maximum Star count (used as 100% baseline)
            bar_length: Progress bar length

        Returns:
            Progress bar string, e.g.: [██████████----------] 60%
        """
        if max_stars <= 0 or stars <= 0:
            return f"[{'-' * bar_length}] 0%"

        # Calculate percentage
        percentage = min(stars / max_stars, 1.0)
        percentage_display = int(percentage * 100)

        # Calculate filled and empty parts
        filled_length = int(bar_length * percentage)
        empty_length = bar_length - filled_length

        # Generate progress bar
        bar = "█" * filled_length + "-" * empty_length

        return f"[{bar}] {percentage_display}%"

    def _count_recommendations(self, analysis_results: List[Dict[str, Any]]) -> Dict[str, int]:
        """Count recommendation types from analysis results."""
        counts = {"recommend": 0, "consider": 0, "avoid": 0}
        for result in analysis_results:
            analysis = result.get("analysis")
            if isinstance(analysis, dict):
                rec = analysis.get("recommendation", "")
                if "recommend" in rec.lower():
                    counts["recommend"] += 1
                elif "avoid" in rec.lower():
                    counts["avoid"] += 1
                else:
                    counts["consider"] += 1
        return counts

    def _collect_maturity_counts(self, analysis_results: List[Dict[str, Any]]) -> Dict[str, int]:
        """Collect maturity distribution counts."""
        counts: Dict[str, int] = {}
        for result in analysis_results:
            analysis = result.get("analysis")
            if isinstance(analysis, dict):
                mat = analysis.get("maturity_assessment", "")
                if mat:
                    mat_lower = mat.lower() if isinstance(mat, str) else str(mat)
                    counts[mat_lower] = counts.get(mat_lower, 0) + 1
        return counts

    def _collect_tech_data(
        self, analysis_results: List[Dict[str, Any]],
    ) -> tuple:
        """Collect language and framework distribution."""
        languages: Dict[str, int] = {}
        frameworks: Dict[str, int] = {}
        for result in analysis_results:
            analysis = result.get("analysis", {})
            tech = analysis.get("tech_stack", {})
            if tech:
                lang = tech.get("language", "")
                if lang and lang != "N/A":
                    languages[lang] = languages.get(lang, 0) + 1
                for fw in tech.get("frameworks", []):
                    frameworks[fw] = frameworks.get(fw, 0) + 1
        return languages, frameworks

    def _format_recommendation_section(self, rec_counts: Dict[str, int]) -> List[str]:
        """Format recommendation statistics section."""
        return [
            "- 🟢 Recommend: {}".format(rec_counts['recommend']),
            "- 🟡 Consider: {}".format(rec_counts['consider']),
            "- 🔴 Avoid: {}".format(rec_counts['avoid']),
        ]

    def _format_maturity_section(self, mat_counts: Dict[str, int]) -> List[str]:
        """Format maturity distribution section."""
        mat_display = {
            "mature": "🔵 Mature",
            "stable": "🟢 Stable",
            "beta": "🟠 Beta",
            "early": "🟡 Early",
        }
        lines = ["", "#### Maturity Distribution"]
        for mat_key, mat_label in mat_display.items():
            count = mat_counts.get(mat_key, 0)
            if count > 0:
                lines.append(f"- {mat_label}: {count}")
        return lines

    def _format_ranking_section(self, analysis_results: List[Dict[str, Any]]) -> List[str]:
        """Format overall ranking section."""
        lines = ["", "#### Overall Ranking",
                 "(Based on Star count, maturity, and recommendation)", ""]
        for i, result in enumerate(analysis_results, 1):
            project = result.get("project", "Unknown")
            stars = result.get("stars", 0)
            analysis = result.get("analysis", {})
            maturity = analysis.get("maturity_assessment", "unknown")
            rec = analysis.get("recommendation", "")
            rec_label = "✅" if "recommend" in rec.lower() else (
                "❌" if "avoid" in rec.lower() else "⚠️")
            lines.append(f"{i}. **{project}** - ⭐ {stars:,} | {maturity} | {rec_label}")
        return lines

    def _format_tech_section(
        self, languages: Dict[str, int], frameworks: Dict[str, int],
    ) -> List[str]:
        """Format technology ecosystem section."""
        lines = []
        if languages:
            lines.extend(["", "#### Technology Ecosystem", "",
                          "**Programming Language Distribution**:"])
            for lang, count in sorted(languages.items(), key=lambda x: x[1], reverse=True):
                lines.append(f"- {lang}: {count} projects")
        if frameworks:
            lines.append("")
            lines.append("**Common Frameworks**:")
            for fw, count in sorted(frameworks.items(), key=lambda x: x[1], reverse=True)[:5]:
                lines.append(f"- {fw} ({count})")
        return lines

    def _generate_overall_assessment(
        self,
        analysis_results: List[Dict[str, Any]],
    ) -> str:
        """Generate overall assessment section"""
        rec_counts = self._count_recommendations(analysis_results)
        mat_counts = self._collect_maturity_counts(analysis_results)
        languages, frameworks = self._collect_tech_data(analysis_results)

        assessment_lines = [
            "Based on the above analysis, here is the overall assessment:",
            "",
            "#### Recommendation Statistics",
        ]
        assessment_lines.extend(self._format_recommendation_section(rec_counts))

        if mat_counts:
            assessment_lines.extend(self._format_maturity_section(mat_counts))

        assessment_lines.extend(self._format_ranking_section(analysis_results))
        assessment_lines.extend(self._format_tech_section(languages, frameworks))

        assessment_lines.extend([
            "",
            "#### Overall Suggestions",
            "Based on comprehensive evaluation of project Star count, tech stack maturity, documentation completeness, etc.,",
            "we recommend prioritizing high-Star projects with comprehensive documentation.",
        ])

        return "\n".join(assessment_lines)

    def _generate_empty_report(self, query: str) -> str:
        """Generate an empty report (when search fails)"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        return f"""# GitHub Project Analysis Report

**Generated at**: {timestamp}
**Search Query**: {query}

---

## Executive Summary

No matching projects found. Please try:
1. Changing the search keyword
2. Checking the GitHub Token configuration
3. Confirming network connectivity is normal

---

*Report automatically generated by GitHub Insight Agent*
"""

    @staticmethod
    def _format_list(items: List[str], indent: str = "- ") -> str:
        """Format a list as a string"""
        if not items:
            return "暂无相关信息"
        return "\n".join(f"{indent}{item}" for item in items)

    @trace(name="report.handle_followup")
    def handle_followup(
        self,
        user_query: str,
    ) -> str:
        """
        Handle user follow-up questions (multi-turn conversation support)

        Args:
            user_query: User follow-up question

        Returns:
            Assistant response
        """
        logger.info(f"Handling followup: {user_query}")

        # Record user question
        self.conversation.add_user_message(user_query)

        # Build context
        context = self._build_followup_context()

        # Call LLM to generate response
        response = self._answer_followup(user_query, context)

        # Record assistant answer
        self.conversation.add_assistant_message(response)

        return response

    def _build_followup_context(self) -> str:
        """
        Build follow-up context

        Returns:
            Formatted context string
        """
        context_parts = []

        # Add current analyzed project information
        if self._current_projects:
            context_parts.append("## Currently Analyzed Projects:")
            for proj in self._current_projects:
                context_parts.append(
                    f"- {proj.get('project', 'Unknown')}: "
                    f"{proj.get('analysis', {}).get('core_function', 'N/A')}"
                )

        # Add conversation history (if any)
        conversation_history = self.conversation.get_context_for_prompt()
        if conversation_history:
            context_parts.append("\n## Conversation History:")
            context_parts.append(conversation_history)

        return "\n".join(context_parts)

    def _resolve_repo_query(self, user_query: str) -> Optional[str]:
        """
        Resolve a repo-related followup question to real data.

        Detects queries mentioning a specific repo (owner/repo or project name)
        and fetches actual repo info from GitHub API.

        Args:
            user_query: User followup question

        Returns:
            Formatted repo info string, or None if not a repo query
        """
        # Pattern: owner/repo (may have Chinese chars after)
        owner_repo_match = re.search(
            r"([a-zA-Z0-9_-]+)/([a-zA-Z0-9_.-]+?)(?:[\s(（]|$|的|是|怎么|如何)",
            user_query,
        )
        if owner_repo_match:
            owner, repo = owner_repo_match.group(1), owner_repo_match.group(2)
            try:
                repo_info = self.analyst.github_tool.get_repo_info(owner, repo)
                return (
                    f"## Repository: {repo_info.full_name}\n"
                    f"- Stars: {repo_info.stargazers_count:,}\n"
                    f"- Forks: {repo_info.forks_count:,}\n"
                    f"- Language: {repo_info.language or 'N/A'}\n"
                    f"- Description: {repo_info.description or 'N/A'}\n"
                    f"- URL: {repo_info.html_url}"
                )
            except Exception:
                pass

        # Pattern: project name followed by star/fork/language keywords
        project_keywords = (
            r"(?:star|stars|fork|forks|language|repo|description|issue|issues"
            r"|commit|commits|pr|pull.?request|release|tag|branch|license|open.?source)"
        )
        name_match = re.search(
            rf"(?:[\s(（]|^)([a-zA-Z][a-zA-Z0-9_.-]{{1,40}})的?[\s(（]?{project_keywords}",
            user_query,
            re.IGNORECASE,
        )
        if name_match:
            project_name = name_match.group(1)
            try:
                repos = self.researcher.github_tool.search_repositories(
                    query=project_name,
                    sort="stars",
                    order="desc",
                    per_page=3,
                )
                if repos:
                    top = repos[0]
                    return (
                        f"## Repository: {top.full_name} (matched from '{project_name}')\n"
                        f"- Stars: {top.stargazers_count:,}\n"
                        f"- Forks: {top.forks_count:,}\n"
                        f"- Language: {top.language or 'N/A'}\n"
                        f"- Description: {top.description or 'N/A'}\n"
                        f"- URL: {top.html_url}"
                    )
            except Exception as e:
                logger.warning(f"Repo search for followup failed: {e}")

        return None

    def _execute_tool_action(self, action: str, params: dict) -> Optional[str]:
        """Execute a tool action based on intent routing result."""
        action_dispatch = {
            "get_repo_info": lambda: self.researcher._execute_get_repo_info(params),
            "search_repositories": lambda: self.researcher._execute_search(params),
            "compare_repositories": lambda: self.researcher._execute_compare(params, analyst=self.analyst),
            "analyze_project": lambda: self.researcher._execute_analyze_project(params, analyst=self.analyst),
        }
        handler = action_dispatch.get(action)
        return handler() if handler else None

    def _fallback_to_llm(self, user_query: str, context: str) -> str:
        """Fallback to LLM chat with context when intent routing doesn't apply."""
        repo_data = self._resolve_repo_query(user_query)
        if repo_data:
            context = f"{context}\n\n## 相关仓库数据\n{repo_data}"

        model_wrapper = self.analyst._get_model_wrapper()
        prompt = f"""请根据以下上下文回答用户的问题。

{context}

## 用户问题
{user_query}

请给出简洁、专业的回答。如果上下文中没有相关信息，请如实告知。"""

        messages = [
            {"name": "system", "content":
             ReportGenerator._build_system_prompt("followup_system_prompt"),
             "role": "system"},
            {"name": "user", "content": prompt, "role": "user"},
        ]

        response = model_wrapper(messages=messages)
        content = self.analyst._extract_response_text(response)
        content = filter_sensitive_output(content)

        logger.info(f"Followup answer generated: {len(content)} chars")

        self.conversation.add_assistant_message(
            content,
            metadata={"type": "followup_response"},
        )

        return content

    def _answer_followup(
        self,
        user_query: str,
        context: str,
    ) -> str:
        """
        Call LLM to answer follow-up questions

        Uses intent understanding: if the query requires a GitHub tool call,
        the researcher's LLM intent router handles it. Otherwise, falls back
        to plain LLM chat with context.
        """
        try:
            intent = self.researcher._understand_intent(user_query)
            action = intent["action"]
            params = intent["params"]

            result = self._execute_tool_action(action, params)
            if result is not None:
                return result
        except Exception as e:
            logger.warning(f"Intent routing failed: {e}, falling back to LLM chat")

        try:
            return self._fallback_to_llm(user_query, context)
        except Exception as e:
            logger.error(f"Failed to generate followup answer: {e}")
            return f"抱歉，生成回答时出错：{e}"

    def get_conversation_history(self) -> List[Dict[str, Any]]:
        """Get conversation history"""
        return self.conversation.get_full_history()

    def export_conversation(self, output_path: str) -> bool:
        """Export conversation records"""
        return self.conversation.export_markdown(output_path)

    def clear_conversation(self) -> None:
        """Clear conversation history"""
        self.conversation.clear_history()
        self._current_projects.clear()
        logger.info("Conversation cleared")

    # ---- Feedback integration (P2-9) ----

    def rate_report(
        self,
        rating: str,
        reason: str = "",
    ) -> bool:
        """
        Rate the last generated report (thumbs up/down).

        Args:
            rating: "good", "bad", or "neutral"
            reason: Optional reason for the rating

        Returns:
            True if rating was recorded successfully
        """
        if rating not in ("good", "bad", "neutral"):
            logger.warning(f"Invalid rating: {rating}")
            return False

        # Get context from last report
        last_report = self.results.get("report", "")
        query = self.results.get("query", "")

        try:
            self.feedback_collector.record(
                rating=rating,
                reason=reason,
                user_input=query,
                assistant_output=last_report[:500],  # Truncate for storage
                agent="pipeline",
                run_id=datetime.now().strftime("%Y%m%d-%H%M%S"),
                metadata={
                    "project_count": len(self.results.get("analysis_results", [])),
                    "tti_total": self.results.get("tti", {}).get("total", 0),
                },
            )

            # Feed back into KPI tracker as user satisfaction signal
            if rating == "good":
                self.kpi_tracker.track_pipeline_kpis(
                    tti_seconds=self.results.get("tti", {}).get("total", 0),
                    success=True,
                )

            logger.info(f"Report rated: {rating} (reason={reason or 'none'})")
            return True
        except Exception as e:
            logger.error(f"Failed to record rating: {e}")
            return False

    def get_feedback_stats(self) -> Dict[str, Any]:
        """Get aggregate feedback statistics."""
        return self.feedback_collector.get_stats()

    def get_recent_feedback(self, limit: int = 10) -> List[Dict[str, Any]]:
        """Get recent feedback entries."""
        return self.feedback_collector.get_recent(limit=limit)

    # ---- Feedback trend analysis (P1) ----

    def get_north_star_metric(self) -> Dict[str, Any]:
        """Return north-star metric: overall positive feedback rate."""
        return self.feedback_trend.get_north_star_metric()

    def get_feedback_trends(self, days: int = 30) -> List[Dict[str, Any]]:
        """Return daily feedback trends for the last N days."""
        return self.feedback_trend.get_daily_trends(days=days)

    def get_trend_summary(self) -> str:
        """Return human-readable trend summary."""
        return self.feedback_trend.get_trend_summary()

    def get_report_stats(self, limit: int = 50) -> List[Dict[str, Any]]:
        """Return recent feedback entries with derived metrics."""
        return self.feedback_trend.get_report_stats(limit=limit)

    def get_results(self) -> Dict[str, Any]:
        """Get workflow execution results"""
        return self.results

    def save_report(self, output_path: str) -> bool:
        """
        Save report to file

        Args:
            output_path: Output file path

        Returns:
            Whether the operation was successful
        """
        if not self.results.get("report"):
            logger.warning("No report to save")
            return False

        try:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(self.results["report"])
            logger.info(f"Report saved to: {output_path}")
            return True
        except Exception as e:
            logger.error(f"Failed to save report: {e}")
            return False
